api.key=em0kX1VqS0l+di5qeTsoM1FpLStd

allowed.origins= http://localhost:4200, \
				https://*.gkdigitalhut.com, \
				https://gkdigitalhut.com
				
content.security.policies=https://*.gkdigitalhut.com https://gkdigitalhut.com http://localhost:4200