api.key=em0kX1VqS0l+di5qeTsoM1FpLStd

allowed.origins= https://*.gkdigitalhut.com, \
				https://gkdigitalhut.com
				
content.security.policies=https://*.gkdigitalhut.com https://gkdigitalhut.com				