version: "3.8"
services:
  gk-digital-hut:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NPM_ENV_BUILD_CMD=npm run build:ssr
        - ARTIFACT_FOLDER=/usr/src/app/dist/gkdigitalhut
        - TARGETPLATFORM=linux/amd64/v3
    image: ghcr.io/gkdigitalhut07/gkdigitalhut:1.0.7
    ports:
      - "4201:4201"
    restart: unless-stopped
    container_name: gkdigitalhut
    mem_limit: 128M
    mem_reservation: 64M
    cpus: 0.125
